#!/bin/bash -eu

function usage()
{
	cat <<EOF
Usage: create-image [<options>] initrd
Usage: create-image [<options>] root
Usage: create-image [<options>] base
Usage: create-image [<options>] test -t <TEST>[,<TEST>,<TEST>...]

Available options:
  -d, --debug             Enable debug output (set -x)
  -e, --keep              Keep image file after a build failure
  -f, --force             Force the creation of an image
  -s, --series <SERIES>   Build an image for series <SERIES>
  -t, --tests <TEST>[,<TEST>,<TEST>...]
                          Add the tests <TEST>[,<TEST>,<TEST>...] to the image
EOF
	exit 2
}


FORCE=0
IMAGE=

KT_KEEP=
KT_SERIES=

while [ $# -gt 0 ] ; do
	case "${1}" in
		-d|--debug)
			set -x
			;;
		-e|--keep)
			# shellcheck disable=SC2034
			KT_KEEP=1
			;;
		-f|--force)
			FORCE=1
			;;
		-s|--series)
			shift
			# shellcheck disable=SC2034
			KT_SERIES=${1}
			;;
		-t|--tests)
			shift
			IFS=',' read -r -a KT_TESTS <<< "${1}"
			;;
		*)
			if [ -n "${IMAGE}" ] ; then
				usage
			fi
			IMAGE=${1}
			;;
	esac
	shift
done

if [ -z "${IMAGE}" ] ; then
	usage
fi

if [ "${IMAGE}" = "test" ] && [ -z "${KT_TESTS:-}" ] ; then
	usage
fi

case "${IMAGE}" in
	initrd)
		KT_FORCE_INITRD=${FORCE}
		;;
	base)
		KT_FORCE_BASE=${FORCE}
		;;
	root)
		KT_FORCE_ROOT=${FORCE}
		;;
	test)
		KT_FORCE_TEST=${FORCE}
		;;
	*)
		echo "+++ ERROR: Unknown image type: ${IMAGE}"
		exit 1
		;;
esac

# shellcheck disable=SC1091
. libs/functions

"kt_create_${IMAGE}"
