#!/bin/bash -eu
#
# Simple wrapper for kernel-test
#

function usage()
{
	cat <<EOF
Usage: kernel-simple-test [-h] <SERIES> [<TEST>] [<TEST>] ...

A simple wrapper for kernel-test.

Runs the specified tests (or 'boot' if no test is specified) using a root image
and kernel of the specified Ubuntu series.

<SERIES>  An Ubuntu series name, like 'trusty'.
<TEST>    A test name, like 'boot'.

Available options:
  -h, --help  Show this help text.
EOF
}

KT_SERIES=
KT_TESTS=""

while [ $# -gt 0 ] ; do
	case "${1}" in
		-h|--help)
			usage
			exit
			;;
		--)
			shift
			break
			;;
		*)
			if [ -z "${KT_SERIES}" ] ; then
				KT_SERIES=${1}
			else
				KT_TESTS="${KT_TESTS},${1}"
			fi
			;;
	esac
	shift
done

if [ -z "${KT_SERIES}" ] ; then
	usage
	exit 2
fi

# The default test to run
KT_TESTS=${KT_TESTS#,}
if [ -z "${KT_TESTS}" ] ; then
	KT_TESTS=boot
fi

# Which kernel to use
KT_KERNEL=~/git/ubuntu/${KT_SERIES}/linux/build/amd64/arch/x86/boot/bzImage

# Run the tests
./kernel-test "${@}" -s "${KT_SERIES}" -k "${KT_KERNEL}" -t "${KT_TESTS}"
